version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: bgg_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  scraper:
    build: .
    depends_on:
      - postgres
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      NUMBER_OF_GAMES: ${NUMBER_OF_GAMES}
      NO_SCRAPER: ${NO_SCRAPER:-0}
    volumes:
      - ./logs:/app/logs
    command: >
      sh -c "
        if [ \"$NO_SCRAPER\" = \"1\" ]; then
          echo 'Scraper disabled â€” starting container only';
          tail -f /dev/null;
        else
          echo 'Starting scraper...';
          python src/main.py -n ${NUMBER_OF_GAMES:-50};
        fi
      "
  
  pipeline:
    build: .
    depends_on:
      - postgres
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
    command: python src/pipeline/extract_db.py
    volumes:
      - .:/app

volumes:
  pgdata:
